### ISSUE TITLE
migrate to AndroidX libraries

### ISSUE THREAD

**Issue by troy-lamerton** [backtrace-labs/backtrace-android#27]
The vast majority of android libraries have migrated to AndroidX already.

Some SDKs are lagging behind, such as the Facebook SDK, which many developers are not happy about. The relevant issue is here: https://github.com/facebook/facebook-android-sdk/issues/591

Support libraries have not received updates since late 2018. See https://developer.android.com/topic/libraries/support-library/revisions#28-0-0

It would be great if backtrace would migrate to androidx libraries soon.

**Comment by rqbacktrace** [comment]
Hi @troy-lamerton, thank you for bringing up this issue! We are investigating this issue and will update here when we have identified next steps.

**Comment by vlussenburg** [comment]
Hello @troy-lamerton .

I know we still need to do this, could you file a ticket at support.backtrace.io in case you want to be alerted when this work is complete?

Thanks,
Vincent.
